# 🧮 NumPy Practice Notebook

This notebook follows structured notes about NumPy basics.
It includes array definitions, attributes, and common operations.
Đọc taking-note tại đây: https://www.notion.so/Numpy-basic-224b7bb79843806f87b3f35685b742b6?source=copy_link 

In [7]:
import numpy as np

## Thuộc tính của mảng
Các thuộc tính thường dùng:
- `.shape`: kích thước mảng
- `.dtype`: kiểu dữ liệu
- `.ndim`: số chiều
- `.size`: tổng số phần tử

In [8]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

# [1 2 3]
# <class 'numpy.ndarray'>
# (3,)
# int64
# 3
# 1

[1 2 3]
<class 'numpy.ndarray'>
(3,)
int64
3
1


## Tạo mảng từ dữ liệu có sẵn (list, tuple)
```python
np.array(object)
```
Chuyển list/tuple thành mảng NumPy.

### Tạo mảng từ list hoặc tuple

In [9]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


## 2 Tạo mảng từ các hàm có sẵn
Một số hàm phổ biến:
- `np.zeros(shape)`
- `np.ones(shape)`
- `np.full(shape, fill_value)`
- `np.arange(start, stop, step)`
- `np.eye(N)`

In [10]:
print(arr)
type(arr)
print(arr.shape)

[1 2 3]
(3,)


### Tạo mảng toàn 0

In [11]:
np.zeros((3, 2))  # 3 hàng, 2 cột
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.]])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Tạo mảng toàn 1

In [12]:
np.ones((2,3))
# array([[1., 1., 1.],
#        [1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

### Tạo mảng với giá trị cố định

In [13]:
np.full((2, 2), 7)
# array([[7, 7],
#        [7, 7]])

array([[7, 7],
       [7, 7]])

### Tạo mảng với np.arange

In [14]:
np.arange(0, 10, 2)
#array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

### Tạo ma trận đơn vị

In [15]:
np.eye(3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Tạo mảng từ list hoặc tuple

In [16]:
arr = np.array([[1, 2], [3, 4]])
arr[0, 1]

np.int64(2)

## Nối mảng 

### Concatenate

In [17]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b), axis=1)

print("Nối theo chiều hàng (axis=0):")
print(c)

print("\nNối theo chiều cột (axis=1):")
print(d)
# Nối theo chiều hàng (axis=0):
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Nối theo chiều cột (axis=1):
# [[1 2 5 6]
#  [3 4 7 8]]

Nối theo chiều hàng (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Nối theo chiều cột (axis=1):
[[1 2 5 6]
 [3 4 7 8]]


### Vstack

In [18]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.vstack((a, b)))
# [[1 2]
#  [3 4]]

[[1 2]
 [3 4]]


### Hstack

In [19]:
a = np.array([[1], [2]])
b = np.array([[3], [4]])

print(np.hstack((a, b)))
# [[1 3]
#  [2 4]]

[[1 3]
 [2 4]]


### Stack

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))  # thêm chiều mới theo hàng
print(np.stack((a, b), axis=1))  # thêm chiều mới theo cột
# [[1 2 3]
#  [4 5 6]]
# [[1 4]
#  [2 5]
#  [3 6]]

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## Reshape

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [22]:

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(-1, 2)  # Tự tính số hàng
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

[[1 2]
 [3 4]
 [5 6]]


### Tạo thêm chiều bằng np.newaxis()

In [23]:
arr = np.array([1, 2, 3])
print(arr.shape)         # (3,)

arr_col = arr[:, np.newaxis]
print(arr_col.shape)     # (3, 1)

arr_row = arr[np.newaxis, :]
print(arr_row.shape)     # (1, 3)

(3,)
(3, 1)
(1, 3)


### Tạo chiều bằng np.expand_dims(arr, axis = )

In [24]:
arr = np.array([1, 2, 3])

expanded_arr = np.expand_dims(arr, axis=0)
print(f'Thêm chiều dọc:{expanded_arr.shape}')  # (1, 3) # thêm chiều trước trục 0 (thêm chiều dọc, tức là thêm hàng bao bọc):
print(expanded_arr)

expanded2 = np.expand_dims(arr, axis=1)
print(expanded2.shape)  # (3, 1)
print(f'Thêm chiều dọc:{expanded2.shape}')  # (3,1) => thêm chiều sau trục 0 (thêm chiều cột, tức là biến vector hàng thành vector cột)
print(expanded2)


Thêm chiều dọc:(1, 3)
[[1 2 3]]
(3, 1)
Thêm chiều dọc:(3, 1)
[[1]
 [2]
 [3]]


### Flatten vs ravel()

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.flatten())  # [1 2 3 4 5 6]
print(arr.ravel())    # [1 2 3 4 5 6]


[1 2 3 4 5 6]
[1 2 3 4 5 6]


### Lọc có điều kiện với np.where(condition, x, y)

In [26]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
idx = np.where(arr > 25) #Nếu chỉ truyền condition, sẽ trả về index.
print(idx) #(array([2, 3, 4]),)
print(arr[idx]) #[30 40 50]


(array([2, 3, 4]),)
[30 40 50]


### Lọc chỉ số của phần tử min/ max

In [27]:
arr = np.array([3, 7, 2, 9, 5])

print("Chỉ số max:", np.argmax(arr))  # 3
print("Chỉ số min:", np.argmin(arr))  # 2


Chỉ số max: 3
Chỉ số min: 2


### Sắp xếp mảng

In [28]:
arr = np.array([[8, 2, 5], [4, 9, 1]])
sorted_arr = np.sort(arr)
print(sorted_arr)
# [[2 5 8]
#  [1 4 9]]

[[2 5 8]
 [1 4 9]]


In [29]:
arr = np.array([30, 10, 20])
idx = np.argsort(arr)
print("Chỉ số sau sắp xếp:", idx)
print("Sắp xếp gián tiếp:", arr[idx])
# Chỉ số sau sắp xếp: [1 2 0]
# Sắp xếp gián tiếp: [10 20 30]

Chỉ số sau sắp xếp: [1 2 0]
Sắp xếp gián tiếp: [10 20 30]


In [30]:
arr = np.array([[8, 2, 5],[1,9,4]])
sorted_arr = np.sort(arr)
print(sorted_arr)
# [[2 5 8]
#  [1 4 9]]
print(sorted_arr[::-1])

[[2 5 8]
 [1 4 9]]
[[1 4 9]
 [2 5 8]]


### Kiểm tra phần tử có trong mảng vs np.isin(phần tử, arr)

In [31]:

arr = np.array([1, 2, 3, 4, 5])
print(3 in arr)  # True
print(np.isin([2, 6], arr))  # [ True False ]


True
[ True False]


### Các phép toán (element-wise)

In [32]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Cộng:", a + b)
print("Trừ:", a - b)
print("Nhân:", a * b)
print("Chia:", a / b)
print("Lũy thừa:", a ** 2)
# Cộng: [5 7 9]
# Trừ: [-3 -3 -3]
# Nhân: [ 4 10 18]
# Chia: [0.25 0.4  0.5 ]
# Lũy thừa: [1 4 9]

Cộng: [5 7 9]
Trừ: [-3 -3 -3]
Nhân: [ 4 10 18]
Chia: [0.25 0.4  0.5 ]
Lũy thừa: [1 4 9]


### Vector or matrix multification


In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B)) 
print(A@B)
# [[19 22]
#  [43 50]]
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Excercises for practice
Following this file: module2/week1/M01W01-Reading_numpy_practice.pdf (page8)


In [34]:
# tính tổng số chẵn trong list
lst= [6,5,7,1,9,2]
print(sum([x for x in lst if x%2==0]))

8


In [36]:
# tổng số chẵn trong array numpy
arr = np.array(lst)
print(arr)
print(type(arr))
np.sum(arr[arr%2 ==0])

[6 5 7 1 9 2]
<class 'numpy.ndarray'>


np.int64(8)

In [37]:
#cộng hai array không cùng shape> broadcasting trước => cộng sau
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])  # shape (2,)

print(a + b)
# [[11 22]
#  [13 24]]

[[11 22]
 [13 24]]


In [38]:
# sắp xếp mảng theo thứ tự tăng dần, giảm dần
import numpy as np
arr = np.array([8, 2, 5])
sorted_arr = np.sort(arr)
print(sorted_arr) #[2 5 8]
print(sorted_arr[::-1]) #[8 5 2]


[2 5 8]
[8 5 2]


In [39]:
#Câu 1: in ra version of numpy
print(np.version.version)

2.2.6


In [40]:
# Câu 2: Tạo mảng một chiều từ 4 đến 9
data = np.arange(4,10)
print(data)

[4 5 6 7 8 9]


In [42]:
# Câu 3: Tạo một mảng boolean 3x3 với tất cả giá trị là True
data = np.full((3,3), True)
print(data)
print(data.shape)
print(data.dtype)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
(3, 3)
bool


In [43]:
# Câu 4: Lấy những phần tử lẻ
data = np.arange(0 , 10)
print(data)
print(data[data%2==1])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [44]:
#Câu 5: Thay thế phần tử bằng -1
data = np.arange(0 , 10) #[0 1 2 3 4 5 6 7 8 9]
print(data)
new = np.where(data%2==1, -1, data) #[ 0 -1  2 -1  4 -1  6 -1  8 -1]
print(new)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [46]:
#Câu 6: Chuyển định dạng (shape) của một ndarray. Chuyển mảng một chiều thành mảng hai chiều dùng reshape 
#Chú ý tích của shape(ndarray) = size(1D array)
data = np.arange(0,10)
new = data.reshape((2,5))
print(data)
print(new)
print(new.shape)
print(data.size)
# [0 1 2 3 4 5 6 7 8 9]
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
# (2, 5)
# 10

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
10


In [49]:
# Câu 7: Xếp chồng 2 mảng theo chiều dọc => vertical => vstack
data1 = np.arange(0,10).reshape((2,5))
data2 = np.full(10,1).reshape((2,5))
print(data1)
print(data2)
stacked = np.vstack((data1,data2))
concatenated = np.concatenate((data1, data2), axis =0)
print(stacked == concatenated)

print(f'Stacked array:{stacked}')
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
# [[1 1 1 1 1]
#  [1 1 1 1 1]]
# Stacked array:[[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
Stacked array:[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
# Câu 8: Xếp chồng 2 mảng theo chiều ngang => hstack
data1 = np.arange(0,10).reshape((2,5))
data2 = np.full(10,1).reshape((2,5))
print(data1)
print(data2)
stacked = np.hstack((data1,data2))
concatenated = np.concatenate((data1, data2), axis =1)
print(stacked == concatenated)

print(f'Stacked array:\n{stacked}')
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
# [[1 1 1 1 1]
#  [1 1 1 1 1]]
# Stacked array:[[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
Stacked array:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [52]:
#Câu 9: Lặp data với repeat() và tile()
import numpy as np

arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 2)
print(repeated)
# [1 1 2 2 3 3]


[1 1 2 2 3 3]


In [53]:
arr = np.array([1,5,7])
repeated = np.repeat(arr, [1, 2, 3])
print(repeated)
# [1 5 5 7 7 7]

[1 5 5 7 7 7]


In [54]:
arr2d = np.array([[1, 2], [3, 4]])
print(np.repeat(arr2d, 2, axis=0))
# [[1 2]
#  [1 2]
#  [3 4]
#  [3 4]]

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [55]:
arr = np.array([1, 2, 3])
tiled = np.tile(arr, 2)
print(tiled)
# [1 2 3 1 2 3]

[1 2 3 1 2 3]


In [57]:
arr2d = np.array([[1, 2], [3, 4]])
tiled = np.tile(arr2d, (2, 3))  # (rows, columns)
print(tiled)
# [[1 2 1 2 1 2]
#  [3 4 3 4 3 4]
#  [1 2 1 2 1 2]
#  [3 4 3 4 3 4]]



[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [59]:
# Câu 10: Lấy phần tử chung của 2 mảng dùng intersect1d()
data1 = np.array([1,2,3,3])
data2 = np.array([7,2,1,8])

intersect_ = np.intersect1d(data1, data2)
print(intersect_) #[1 2]


[1 2]


In [60]:
# Câu 11: Xoá phần tử từ một mảng mà tồn tại trong một mảng khác
data1 = np.arange(1,6)
data2 = np.array([1,5,9])
out = np.setdiff1d(data1, data2)
print(out) #[2 3 4]

[2 3 4]


In [68]:
# Câu 12: Lấy tất cả vị trí nơi giá trị các phần tử của hai mảng giống nhau
data1 = np.arange(1,7)
data2 = np.array([1,6]).repeat(3)
print(data1)
print(data2)
match = np.where(data1 == data2)
print(match[0])

[1 2 3 4 5 6]
[1 1 1 6 6 6]
[0 5]


In [78]:
# Câu 13:  Lấy tất cả các giá trị trong một phạm vi cho trước
data = np.array([1,8,3,9,7,6])
index = np.where(data>=7)
print(index)
print(data[index])

(array([1, 3, 4]),)
[8 9 7]


In [89]:
import numpy as np

# Hàm so sánh
def get_max(x, y):
    return x if x >= y else y

# Hai mảng dữ liệu
data1 = np.array([5, 3, 8, 2, 7])
data2 = np.array([2, 7, 3, 1, 8])

# Vector hóa hàm
pair_max = np.vectorize(get_max)

# Áp dụng lên mảng
out = pair_max(data1, data2)
print(out)  # [5 7 8 2 8]


[5 7 8 2 8]


In [ ]:
#Câu 15: Hoán đổi các cột trong mảng hai chiều

data = np.arange(9).reshape((3,3))
print(data)

print(data[:,[1, 0, 2]]) #lấy tất cả các hàng, hoá đổi vị trí cột 



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [94]:
# Câu 16: Hoán đổi các dòng trong mảng hai chiều

data = np.arange(9).reshape((3,3))
print(data)

print(data[[1, 0, 2], :]) #hoán đổi vị trí dòng, lấy tất cả các cột

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [ ]:
# Câu 17: Đảo ngược các phần tử của các cột trong mảng hai chiều
data = np.arange(9).reshape((3,3))
print(data)

print(data[: : -1, :]) #dùng ::-1 để đảo ngược


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [100]:
# Câu 18: Đảo ngược các phần tử của các hàng trong mảng hai chiều
data = np.arange(9).reshape((3,3))
print(data)

print(data[: , :: -1]) #dùng ::-1 để đảo ngược

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [103]:
# Câu 19: Tạo mảng hai chiều chứa số ngẫu nhiên (kiểu số lẻ)
data= np.random.random((2,3)) #gía trị random from 0 to 1
print(data)

data1= np.random.uniform(5,10,size = (2,3)) #gía trị random from 5 to 10
print(data1)

[[0.37331209 0.59041303 0.05784332]
 [0.64756843 0.93062816 0.88758228]]
[[5.53253903 5.70461941 6.56405571]
 [8.10791685 8.48004532 5.12745401]]


### Excercises about vector

Following this file: module2/week1/M01W01-Reading_numpy_practice.pdf (page19)

In [105]:
#Câu 1: Tính độ dài của một vector
u = np.array([1,2,4,2])
vec_mag = np.linalg.norm(u)
print(vec_mag)

5.0


In [112]:
# Câu 2. Phép cộng và trừ giữa hai vector
data_x = np.arange(1,5)
data_y = np.arange(5, 9)

print(f'Addition of 2 vectors:{data_x+ data_y}')
print(f'Subtraction of 2 vectors:{data_x - data_y}')
print(f'Hadamard of 2 vectors:{data_x * data_y}')
print(f'Chia of 2 vectors:{data_x / data_y}')

Addition of 2 vectors:[ 6  8 10 12]
Subtraction of 2 vectors:[-4 -4 -4 -4]
Hadamard of 2 vectors:[ 5 12 21 32]
Chia of 2 vectors:[0.2        0.33333333 0.42857143 0.5       ]


In [114]:
#Tính tích vô hướng (dot product) giữa hai vector
data_x = np.arange(1,5)
data_y = np.arange(5, 9)
print(f'Dot product: {data_x.dot(data_y)}')

Dot product: 70


In [128]:
# Các phép tính cơ bản trên ma trận
import numpy as np
a = np.arange(1,7).reshape((2,3))
b = np.arange(5, 11).reshape((2,3))
print(a)
print('\n')
print(b)

print("Cộng:\n", a + b)
print("Trừ:\n", a - b)
print("Nhân:\n", a * b)
print("Chia:\n", a / b)
print("Transpose:\n", a.T)


[[1 2 3]
 [4 5 6]]


[[ 5  6  7]
 [ 8  9 10]]
Cộng:
 [[ 6  8 10]
 [12 14 16]]
Trừ:
 [[-4 -4 -4]
 [-4 -4 -4]]
Nhân:
 [[ 5 12 21]
 [32 45 60]]
Chia:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([1, 2, 3])
new_arr = np.sort(arr)
print(new_arr)  # [1 2 3]
print(arr is new_arr) # False ⇒ mảng mới
print(id(arr))
print(id(new_arr))  
#4394550448
#4406832912

[1 2 3]
False
4394550448
4406832912


In [131]:
arr = np.array([1, 2, 3])
# arr.append(4)  ❌ Lỗi: không có method này
# Giải pháp: tạo mảng mới
arr2 = np.append(arr, 4)
print(id(arr)==id(arr2))

False


In [132]:
import numpy as np

arr = np.array([3, 1, 2])

# Sử dụng np.sort (trả về mảng mới)
sorted_arr = np.sort(arr)
print("np.sort(arr):", sorted_arr)  # [1 2 3]
print("arr sau np.sort:", arr)      # [3 1 2] (không đổi)

# Sử dụng arr.sort() (in-place)
arr.sort()
print("arr sau arr.sort():", arr)   # [1 2 3]

np.sort(arr): [1 2 3]
arr sau np.sort: [3 1 2]
arr sau arr.sort(): [1 2 3]
