# 🧮 NumPy Practice Notebook

This notebook follows structured notes about NumPy basics.
It includes array definitions, attributes, and common operations.

## 2.1 Tạo mảng từ dữ liệu có sẵn (list, tuple)
```python
np.array(object)
```
Chuyển list/tuple thành mảng NumPy.

### Tạo mảng từ list hoặc tuple

In [1]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


## 1. Thuộc tính của mảng
Các thuộc tính thường dùng:
- `.shape`: kích thước mảng
- `.dtype`: kiểu dữ liệu
- `.ndim`: số chiều
- `.size`: tổng số phần tử

### Tạo mảng từ list hoặc tuple

In [2]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

# [1 2 3]
# <class 'numpy.ndarray'>
# (3,)
# int64
# 3
# 1

[1 2 3]
<class 'numpy.ndarray'>
(3,)
int64
3
1


## 2.2 Tạo mảng từ các hàm có sẵn
Một số hàm phổ biến:
- `np.zeros(shape)`
- `np.ones(shape)`
- `np.full(shape, fill_value)`
- `np.arange(start, stop, step)`
- `np.eye(N)`

In [3]:
print(arr)
type(arr)
print(arr.shape)

[1 2 3]
(3,)


### Tạo mảng toàn 0

In [4]:
np.zeros((3, 2))  # 3 hàng, 2 cột
# array([[0., 0.],
#        [0., 0.],
#        [0., 0.]])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Tạo mảng toàn 1

In [5]:
np.ones((2,3))
# array([[1., 1., 1.],
#        [1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

### Tạo mảng với giá trị cố định

In [6]:
np.full((2, 2), 7)
# array([[7, 7],
#        [7, 7]])

array([[7, 7],
       [7, 7]])

### Tạo mảng với np.arange

In [7]:
np.arange(0, 10, 2)
#array([0, 2, 4, 6, 8])

array([0, 2, 4, 6, 8])

### Tạo ma trận đơn vị

In [8]:
np.eye(3)
# array([[1., 0., 0.],
#        [0., 1., 0.],
#        [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Tạo mảng từ list hoặc tuple

In [27]:
arr = np.array([[1, 2], [3, 4]])
arr[0, 1]

np.int64(2)

### Tạo mảng từ list hoặc tuple

In [10]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b), axis=1)

print("Nối theo chiều hàng (axis=0):")
print(c)

print("\nNối theo chiều cột (axis=1):")
print(d)
# Nối theo chiều hàng (axis=0):
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Nối theo chiều cột (axis=1):
# [[1 2 5 6]
#  [3 4 7 8]]

Nối theo chiều hàng (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Nối theo chiều cột (axis=1):
[[1 2 5 6]
 [3 4 7 8]]


### Tạo mảng từ list hoặc tuple

In [11]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])

print(np.vstack((a, b)))
# [[1 2]
#  [3 4]]

[[1 2]
 [3 4]]


### Tạo mảng từ list hoặc tuple

In [12]:
a = np.array([[1], [2]])
b = np.array([[3], [4]])

print(np.hstack((a, b)))
# [[1 3]
#  [2 4]]

[[1 3]
 [2 4]]


### Tạo mảng từ list hoặc tuple

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))  # thêm chiều mới theo hàng
print(np.stack((a, b), axis=1))  # thêm chiều mới theo cột
# [[1 2 3]
#  [4 5 6]]
# [[1 4]
#  [2 5]
#  [3 6]]

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### Tạo mảng từ list hoặc tuple

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


### Tạo mảng từ list hoặc tuple

In [15]:

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(-1, 2)  # Tự tính số hàng
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

[[1 2]
 [3 4]
 [5 6]]


### Tạo mảng từ list hoặc tuple

In [16]:
arr = np.array([1, 2, 3])
print(arr.shape)         # (3,)

arr_col = arr[:, np.newaxis]
print(arr_col.shape)     # (3, 1)

arr_row = arr[np.newaxis, :]
print(arr_row.shape)     # (1, 3)

(3,)
(3, 1)
(1, 3)


### Tạo mảng từ list hoặc tuple

In [17]:
arr = np.array([1, 2, 3])

expanded_arr = np.expand_dims(arr, axis=0)
print(f'Thêm chiều dọc:{expanded_arr.shape}')  # (1, 3) # thêm chiều trước trục 0 (thêm chiều dọc, tức là thêm hàng bao bọc):
print(expanded_arr)

expanded2 = np.expand_dims(arr, axis=1)
print(expanded2.shape)  # (3, 1)
print(f'Thêm chiều dọc:{expanded2.shape}')  # (3,1) => thêm chiều sau trục 0 (thêm chiều cột, tức là biến vector hàng thành vector cột)
print(expanded2)


Thêm chiều dọc:(1, 3)
[[1 2 3]]
(3, 1)
Thêm chiều dọc:(3, 1)
[[1]
 [2]
 [3]]


### Tạo mảng từ list hoặc tuple

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.flatten())  # [1 2 3 4 5 6]
print(arr.ravel())    # [1 2 3 4 5 6]


[1 2 3 4 5 6]
[1 2 3 4 5 6]


### Tạo mảng từ list hoặc tuple

In [19]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
idx = np.where(arr > 25) #Nếu chỉ truyền condition, sẽ trả về index.
print(idx) #(array([2, 3, 4]),)
print(arr[idx]) #[30 40 50]


(array([2, 3, 4]),)
[30 40 50]


### Tạo mảng từ list hoặc tuple

In [20]:
arr = np.array([3, 7, 2, 9, 5])

print("Chỉ số max:", np.argmax(arr))  # 3
print("Chỉ số min:", np.argmin(arr))  # 2


Chỉ số max: 3
Chỉ số min: 2


### Tạo mảng từ list hoặc tuple

In [21]:
arr = np.array([[8, 2, 5], [4, 9, 1]])
sorted_arr = np.sort(arr)
print(sorted_arr)
# [[2 5 8]
#  [1 4 9]]

[[2 5 8]
 [1 4 9]]


### Tạo mảng từ list hoặc tuple

In [22]:
arr = np.array([30, 10, 20])
idx = np.argsort(arr)
print("Chỉ số sau sắp xếp:", idx)
print("Sắp xếp gián tiếp:", arr[idx])
# Chỉ số sau sắp xếp: [1 2 0]
# Sắp xếp gián tiếp: [10 20 30]

Chỉ số sau sắp xếp: [1 2 0]
Sắp xếp gián tiếp: [10 20 30]


### Tạo mảng từ list hoặc tuple

In [23]:

arr = np.array([1, 2, 3, 4, 5])
print(3 in arr)  # True
print(np.isin([2, 6], arr))  # [ True False ]


True
[ True False]


### Tạo mảng từ list hoặc tuple

In [24]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Cộng:", a + b)
print("Trừ:", a - b)
print("Nhân:", a * b)
print("Chia:", a / b)
print("Lũy thừa:", a ** 2)
# Cộng: [5 7 9]
# Trừ: [-3 -3 -3]
# Nhân: [ 4 10 18]
# Chia: [0.25 0.4  0.5 ]
# Lũy thừa: [1 4 9]

Cộng: [5 7 9]
Trừ: [-3 -3 -3]
Nhân: [ 4 10 18]
Chia: [0.25 0.4  0.5 ]
Lũy thừa: [1 4 9]


### Tạo mảng từ list hoặc tuple

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B)) 
print(A@B)
# [[19 22]
#  [43 50]]
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Phép toán trừ (element-wise)

In [26]:
arr = numpy.array([-1,1,2,34,43])
print(arr)
print(type(arr))

print(arr.sort())



NameError: name 'numpy' is not defined

### Tạo mảng từ list hoặc tuple

In [ ]:
arr = np.array([[8, 2, 5],[1,9,4]])
sorted_arr = np.sort(arr)
print(sorted_arr)
# [[2 5 8]
#  [1 4 9]]
print(sorted_arr[::-1])

### Tạo mảng từ list hoặc tuple

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
idx = np.where(arr > 25) #Nếu chỉ truyền condition, sẽ trả về index.
print(idx) #(array([2, 3, 4]),)
print(arr[idx]) #[30 40 50]

In [ ]:
# tính tổng số chẵn trong list
lst= [6,5,7,1,9,2]
print(sum([x for x in lst if x%2==0]))

### Truy cập phần tử với indexing/slicing

In [ ]:
# tổng số chẵn trong array numpy
arr = numpy.array(lst)
print(arr)
print(type(arr))
np.sum(arr[arr%2 ==0])

### Tạo mảng từ list hoặc tuple

In [ ]:
#cộng hai array không cùng shape> broadcasting trước => cộng sau
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])  # shape (2,)

print(a + b)
# [[11 22]
#  [13 24]]

### Tạo mảng từ list hoặc tuple

In [ ]:
# sắp xếp mảng theo thứ tự tăng dần, giảm dần
import numpy as np
arr = np.array([8, 2, 5])
sorted_arr = np.sort(arr)
print(sorted_arr) #[2 5 8]
print(sorted_arr[::-1]) #[8 5 2]


In [ ]:
#Câu 1: in ra version of numpy
print(numpy.version.version)

### Tạo mảng với np.arange

In [ ]:
# Câu 2: Tạo mảng một chiều từ 4 đến 9
data = np.arange(4,10)
print(data)

In [ ]:
# Câu 3: Tạo một mảng boolean 3x3 với tất cả giá trị là True
data = numpy.full((3,3), True)
print(data)
print(data.shape)
print(data.dtype)

### Tạo mảng với np.arange

In [ ]:
# Câu 4: Lấy những phần tử lẻ
data = np.arange(0 , 10)
print(data)
print(data[data%2==1])

### Tạo mảng với np.arange

In [ ]:
#Câu 5: Thay thế phần tử bằng -1
data = np.arange(0 , 10) #[0 1 2 3 4 5 6 7 8 9]
print(data)
new = np.where(data%2==1, -1, data) #[ 0 -1  2 -1  4 -1  6 -1  8 -1]
print(new)

### Tạo mảng với np.arange

In [ ]:
#Câu 6: Chuyển định dạng (shape) của một ndarray. Chuyển mảng một chiều thành mảng hai chiều dùng reshape 
#Chú ý tích của shape(ndarray) = size(1D array)
data = np.arange(0,10)
new = data.reshape((2,5))
print(data)
print(new)
print(new.shape)
print(data.size)
# [0 1 2 3 4 5 6 7 8 9]
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
# (2, 5)
# 10

### Tạo mảng với giá trị cố định

In [ ]:
# Câu 7: Xếp chồng 2 mảng theo chiều dọc => vertical => vstack
data1 = np.arange(0,10).reshape((2,5))
data2 = np.full(10,1).reshape((2,5))
print(data1)
print(data2)
stacked = numpy.vstack((data1,data2))
concatenated = numpy.concatenate((data1, data2), axis =0)
print(stacked == concatenated)

print(f'Stacked array:{stacked}')
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
# [[1 1 1 1 1]
#  [1 1 1 1 1]]
# Stacked array:[[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]

### Tạo mảng với giá trị cố định

In [ ]:
# Câu 8: Xếp chồng 2 mảng theo chiều ngang => hstack
data1 = np.arange(0,10).reshape((2,5))
data2 = np.full(10,1).reshape((2,5))
print(data1)
print(data2)
stacked = numpy.hstack((data1,data2))
concatenated = numpy.concatenate((data1, data2), axis =1)
print(stacked == concatenated)

print(f'Stacked array:\n{stacked}')
# [[0 1 2 3 4]
#  [5 6 7 8 9]]
# [[1 1 1 1 1]
#  [1 1 1 1 1]]
# Stacked array:[[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]

### Tạo mảng từ list hoặc tuple

In [ ]:
#Câu 9: Lặp data với repeat() và tile()
import numpy as np

arr = np.array([1, 2, 3])
repeated = np.repeat(arr, 2)
print(repeated)
# [1 1 2 2 3 3]


### Tạo mảng từ list hoặc tuple

In [ ]:
arr = np.array([1,5,7])
repeated = np.repeat(arr, [1, 2, 3])
print(repeated)
# [1 5 5 7 7 7]

### Tạo mảng từ list hoặc tuple

In [ ]:
arr2d = np.array([[1, 2], [3, 4]])
print(np.repeat(arr2d, 2, axis=0))
# [[1 2]
#  [1 2]
#  [3 4]
#  [3 4]]

### Tạo mảng từ list hoặc tuple

In [ ]:
arr = np.array([1, 2, 3])
tiled = np.tile(arr, 2)
print(tiled)
# [1 2 3 1 2 3]

### Tạo mảng từ list hoặc tuple

In [ ]:
arr2d = np.array([[1, 2], [3, 4]])
tiled = np.tile(arr2d, (2, 3))  # (rows, columns)
print(tiled)
# [[1 2 1 2 1 2]
#  [3 4 3 4 3 4]
#  [1 2 1 2 1 2]
#  [3 4 3 4 3 4]]



In [ ]:
# Câu 10: Lấy phần tử chung của 2 mảng dùng intersect1d()
data1 = numpy.array([1,2,3,3])
data2 = numpy.array([7,2,1,8])

intersect_ = numpy.intersect1d(data1, data2)
print(intersect_) #[1 2]


In [ ]:
# Xoá phần tử từ một mảng mà tồn tại trong một mảng khác
data1 = numpy.arange(1,6)
data2 = numpy.array([1,5,9])
out = numpy.setdiff1d(data1, data2)
print(out) #[2 3 4]